name: Flutter Build (Nix Flake Version)

on:
  workflow_dispatch:
  push:
    branches:
      - build
      - gh_flake

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

  dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Dependencies
        run: nix develop --command flutter pub get

  format-check:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: dart format --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Static Code Analysis
        run: flutter analyze

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    outputs:
      apk_arm64: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      apk_armeabi: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build APK
        run: nix develop --command flutter build apk --release --split-per-abi

      - name: Save APK Paths
        id: apk_paths
        run: echo "apk_arm64=build/app/outputs/apk/release/app-arm64-v8a-release.apk" >> $GITHUB_ENV && echo "apk_armeabi=build/app/outputs/apk/release/app-armeabi-v7a-release.apk" >> $GITHUB_ENV

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload APK (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release.apk
          path: ${{ needs.build.outputs.apk_arm64 }}

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release.apk
          path: ${{ needs.build.outputs.apk_armeabi }}
